### PR TITLE
Add summary slides

### PR DESCRIPTION
**Pull request by bradyrx**
This PR adds the summary slides for the intro to the workshop.

I'm trying out `rise` here which auto-converts jupyter notebooks into reveal.js slides. This doesn't make it very easy for users to check out the slides outside of the tutorial, but it will be nice for the tutorial since we'll have executable code cells.

### CODE REVIEW

**Comment by bradyrx** [comment]
Once I request a review, the best way I think to check this out is to clone the repo, install rise, and then open jupyter notebook (not lab) and click the "enter RISE slideshow" button to look through.

**Comment by bradyrx** [comment]
Okay this is ready for review for whoever has time to give it a look before Wednesday! @andersy005, @aaronspring, @kpegion.

Instructions are in the README attached to this PR. You can install the conda environment which includes `rise` for the slides and the most recent master branch `climpred`. Then activate the environment and run `python scripts/rise_json.py` to install the reveal.js theme. Then open a notebook and run the reveal slides from the button at the top of the notebook.

Let me know if you have any thoughts but I think it's safe as is. I can incorporate edits for Wed if you give thoughts by early afternoon Tuesday. Thanks!

**Comment by andersy005** [comment]
> Once I request a review, the best way I think to check this out is to clone the repo, install rise, and then open jupyter notebook (not lab) and click the "enter RISE slideshow" button to look through.

Fixed it for you with my binder: [Binder](https://mybinder.org/v2/gh/bradyrx/climpred_workshop/add_summary_slides) :) 

I will take a look at the slides some time today, and will get back to you.

**Comment by bradyrx** [comment]
Nice @andersy005, I didn't realize `rise` would work through binder! But I guess it makes sense since it installs the local environment. Any ideas on how to install themes with the binder?

**Comment by andersy005** [comment]
> Any ideas on how to install themes with the binder?

Create a new script called `postBuild` and put it in  `binder/` folder 


The content of this file looks like:

```bash
#!/bin/bash
set -euo pipefail

# Install Reveal theme
python scripts/rise_json.py
```

Binder will execute the `postBuild` script after everything is installed.  Remember to make `postBuild` executable (prior committing it) with:

```bash
chmod +x postBuild
```

**Pull request merged**
